version: "3.9"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - database-volume:/var/lib/postgresql/data
volumes:
  database-volume:
networks:
  default:
    name: indefinite-studies-environment